### ISSUE TITLE
TypeError: Note must be a string, not TypeError

### ISSUE THREAD

**Issue by colinmford** [roboDocs/MutatorScale#2]
```Traceback (most recent call last):
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
    self.action_(notification.object())
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 505, in action_
    self.callback(sender)
  File "scaleFast.py", line 715, in _inputGlyphs
  File "scaleFast.py", line 1209, in _updatePreview
  File "scaleFast.py", line 756, in _buildScaledGlyphs
  File "scaleFast.py", line 763, in _retrieveScaledGlyph
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 262, in getScaledGlyph
    instanceGlyph = self._getInstanceGlyph(targetLocation, mutatorMasters)
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 291, in _getInstanceGlyph
    return ErrorGlyph('Interpolation', errorMessage)
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/errorGlyph.py", line 30, in __new__
    newGlyph.__init__(errorName, report, size, upm)
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/errorGlyph.py", line 35, in __init__
    self.note = report
  File "/Users/colinmford/Library/Application Support/RoboFont/external_packages/fontParts/base/base.py", line 101, in __set__
    setter(value)
  File "/Users/colinmford/Library/Application Support/RoboFont/external_packages/fontParts/base/glyph.py", line 2296, in _set_base_note
    value = normalizers.normalizeGlyphNote(value)
  File "/Users/colinmford/Library/Application Support/RoboFont/external_packages/fontParts/base/normalizers.py", line 947, in normalizeGlyphNote
    % type(value).__name__)
TypeError: Note must be a string, not TypeError.
```

Getting this traceback when there is an interpolation error in ScaleFast. It seems as if MutatorScale is trying to assign the TypeError it gets back from MutatorMath as a note on the ErrorGlyph RGlyph object, but FontParts is enforcing the type to be a string. 

Changing line 35 to pass a string instead of a TypeError would solve the issue. Will make a PR. https://github.com/roboDocs/MutatorScale/blob/597708e5a4bd753fcebcf3faf9dc5a5804cf027a/lib/mutatorScale/objects/errorGlyph.py#L35

**Comment by colinmford** [comment]
PR #3 should fix this issue

**Comment by colinmford** [comment]
Left issue in roboDocs/ScaleFast#13

**Comment by colinmford** [comment]
Thanks, @typemytype!
